#hub:
#  image:
#    name: jupyterhub/jupyterhub
#    tag: 1.4.2
#  extraConfig:
#    cull:
#      enabled: true
#      timeout: 600
#      every: 300
#singleuser:
#  defaultUrl: "/lab"
#  extraEnv:
#    JUPYTERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"