apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: crash-sa2-join
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  configmaps:
  - name: shared-data
    namespace: ""
  - name: crash-sa2-join-data
    namespace: ""
  environment:
    name: python
    namespace: ""
  functionTimeout: 600
  idletimeout: 120
  package:
    functionName: crash_sa2_join.main
    packageref:
      name: crash-sa2-join
      namespace: ""
  requestsPerPod: 1
  resources: {}
  secrets:
  - name: es-secret
    namespace: ""
