apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: crash-sample
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  configmaps:
  - name: shared-data
    namespace: ""
  environment:
    name: python
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: crash_sample.main
    packageref:
      name: crash-sample
      namespace: ""
  requestsPerPod: 1
  resources: {}
  secrets:
  - name: es-secret
    namespace: ""
