apiVersion: fission.io/v1
kind: MessageQueueTrigger
metadata:
  creationTimestamp: null
  name: add-weather-observations
spec:
  contentType: application/json
  cooldownPeriod: 30
  errorTopic: errors
  functionref:
    functionweights: null
    name: addweatherdata
    type: name
  maxReplicaCount: 100
  maxRetries: 3
  messageQueueType: kafka
  metadata:
    bootstrapServers: my-cluster-kafka-bootstrap.kafka.svc:9092
    consumerGroup: my-group
  minReplicaCount: 0
  mqtkind: keda
  pollingInterval: 5
  topic: weather
