include:
- ./functions/api/crash_sample.zip
kind: ArchiveUploadSpec
name: functions-api-crash-sample-zip-WoaC

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: crash-sample
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-api-crash-sample-zip-WoaC
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-16T08:19:38Z"
