include:
- ./functions/api/sortmortalityfertilitydata.zip
kind: ArchiveUploadSpec
name: functions-api-sortmortalityfertilitydata-zip-I7mG

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: sortmortalityfertilitydata
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-api-sortmortalityfertilitydata-zip-I7mG
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-19T06:33:38Z"
