include:
- ./functions/addepadata.zip
kind: ArchiveUploadSpec
name: functions-addepadata-zip-sV5g

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: addepadata
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-addepadata-zip-sV5g
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-04-20T12:48:49Z"
