include:
- ./functions/api/weatherdata.zip
kind: ArchiveUploadSpec
name: functions-api-weatherdata-zip-z0Zg

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: getweatherdata
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-api-weatherdata-zip-z0Zg
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-19T04:07:10Z"
