include:
- ./functions/crash_sa2_join.zip
kind: ArchiveUploadSpec
name: functions-crash-sa2-join-zip-L1LP

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: crash-sa2-join
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-crash-sa2-join-zip-L1LP
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-16T08:16:14Z"
