include:
- ./functions/api/mortalityfertilitydata.zip
kind: ArchiveUploadSpec
name: functions-api-mortalityfertilitydata-zip-DwUi

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: mortalityfertilitydata
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-api-mortalityfertilitydata-zip-DwUi
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-19T04:07:10Z"
