include:
- ./functions/api/crash_aggregation.zip
kind: ArchiveUploadSpec
name: functions-api-crash-aggregation-zip-tMj3

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: crash-aggregation
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://functions-api-crash-aggregation-zip-tMj3
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-16T08:21:36Z"
