apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: crash-aggregation-nested
spec:
  createingress: true
  functionref:
    functionweights: null
    name: crash-aggregation
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /crashes/by/{by-field}/{aggregation}/{aggregation-field}
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /crashes/by/{by-field}/{aggregation}/{aggregation-field}
