apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: wharvester
spec:
  createingress: true
  functionref:
    functionweights: null
    name: wharvester
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /wharvester
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /wharvester
