apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: sa2-geometry
spec:
  createingress: true
  functionref:
    functionweights: null
    name: sa2-geometry
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /sa2/geometry
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /sa2/geometry
