apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: mfsortdata
spec:
  createingress: true
  functionref:
    functionweights: null
    name: sortmortalityfertilitydata
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /sortmortalityfertilitydata/attribute/{attribute:[a-zA-Z.-_]*}
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /sortmortalityfertilitydata/attribute/{attribute:[a-zA-Z.-_]*}
